### ISSUE TITLE
Please publish the NPM and update the dependencies in vscode-brightscript-language

### ISSUE THREAD

**Issue by evgygor** [TwitchBronBron/brightscript-formatter#12]
Please publish the NPM and update the brightscript-formatter dependency in [vscode-brightscript-language](https://github.com/TwitchBronBron/vscode-brightscript-language).

Thank a lot.

**Comment by TwitchBronBron** [comment]
[Version 1.3.0 of brightscript-formatter](https://www.npmjs.com/package/brightscript-formatter) has been released. Also, [version 1.2.2 of vscode-brightscript-language](https://marketplace.visualstudio.com/items?itemName=celsoaf.brightscript) has been released which uses brightscript-formatter version  1.3.0.

**Comment by evgygor** [comment]
Thanks a lot!
