### ISSUE TITLE
multi-line 'else if' statements not formatted.

### ISSUE THREAD

**Issue by evgygor** [TwitchBronBron/brightscript-formatter#8]
the code below not formatted:
_else if () then
foo()
bar()
end if_ 

when 'if' started on new line the code formatted well:
else 
 if () then
 ___foo()
 ___bar()
 end if

**Comment by TwitchBronBron** [comment]
@evgygor Can you provide a fully functional code snippet, or create a fork with a runnable unit test showing how this fails (you can just add a new test to [BrightScriptFormatter.spec.ts](https://github.com/TwitchBronBron/brightscript-formatter/blob/master/src/BrightScriptFormatter.spec.ts))? I tried guessing what you were doing above that starting `else if ()`. 

This block of code formats properly in my tests. 

```brightscript
if true then
    doSomething()
else if () then
    foo()
    bar()
end if
```

**Comment by evgygor** [comment]
@TwitchBronBron currently, I cannot reproduce the issue . I suggest the issue may be closed.

**Comment by evgygor** [comment]
I rechecked - works well.
Thanks
